version: '3.5'

services:

  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  kafka:
    image: wurstmeister/kafka
    hostname: 127.0.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "customers:6:1"
    restart: on-failure

  kafkaviewer:
      image: obsidiandynamics/kafdrop
      depends_on:
        - kafka
      ports:
        - "9003:9000"
      environment:
        - ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_BROKERCONNECT=kafka:9092
        - SERVER_SERVLET_CONTEXTPATH=/

  customerscgen: 
    image: vitkodmitriy/customer-score-generator:1

  customerwebsrv:
    image: vitkodmitriy/customer-web-service:1
    ports:
      - "8008:8008"  

  customerwebsrv1:
    image: vitkodmitriy/customer-web-service:1

  customerwebsrv2:
    image: vitkodmitriy/customer-web-service:1

  customerwebsrv3:
    image: vitkodmitriy/customer-web-service:1


  customerwebsrv4:
    image: vitkodmitriy/customer-web-service:1


  customerwebsrv5:
    image: vitkodmitriy/customer-web-service:1
